def tokenise(words):
    punctuation = {
        "' ":" ' ",      
        " '":" ' ",
        "'d":" 'd",  
        "'D":" 'D",  
        "'s":" 's",  
        "'S":" 'S",  
        "'m":" 'm",  
        "'M":" 'M",  
        "'ll":" 'll",
        "'LL":" 'LL",
        "'re":" 're",        
        "'RE":" 'RE",        
        "'ve":" 've",        
        "'VE":" 'VE",        
        "n't":" n't",
        "N'T":" N'T",
        "!":" ! ",
        "?":" ? ",
        "#":" # ",
        "%":" % ",
        "&":" & ",
        "\\":" \ ",
        "*":" * ",
        "+":" + ",
        "/":" / ", 
        ":":" : ",
        ";":" ; ",
        "=":" = ",
        "@":" @ ",
        "^":" ^ ",
        "_":" _ ",
        "`":" ` ",
        "|":" | ",
        "~":" ~ ",
        ' "': ' `` ',
        '" ': ' " ',
        '".': ' " .',
        '",':' " ,',
        "-":" - ",
        '-  -':'--',
        '. ':' . ',
        '."':'. "',
        ".'":". '",
        '.)':'. )',
        '.]':'. ]',
        '.}':'. }',
        '.>':'. >',
        '..':'. .',
        '. . .':' ... ',
        '.  .  .':' ... ',
        ',':' , ',
        '(':' -LRB- ',
        '[':' -LSB- ',
        '{':' -LCB- ',
        ')':' -RRB- ',
        ']':' -RSB- ',
        '}':' -RCB- ',
        '<':' < ',
        '>':' > ',
        '\t':' ',
        '$':' $ ',
        '£':' £ ',
        ' cannot ':' can not ',
        ' Cannot ':' Can not ',
        " d'ye ":" d' ye ",
        " D'ye ":" D' ye ",
        " gimme ":" gim me ",
        " Gimme ":" Gim me ",
        " gonna ":" gon na ",
        " Gonna ":" Gon na ",
        " lemme ":" lem me ",
        " Lemme ":" Lem me ",
        " more'n ":" more 'n ",
        " More'n ":" More 'n ",
        " 'Tis ":" 'T is ",
        " 'tis ":" 't is ",
        " 'Twas ":" 'T was ",
        " 'twas ":" 't was ",
        ' wanna ': ' wan na ',
        ' Wanna ': ' Wan na ',
        ' whaddya ': ' wha dd ya ',
        ' Whaddya ': ' Wha dd ya ',
        ' whatcha ':' wha t cha ',
        ' Whatcha ':' Wha t cha ',
        ' aint ':" ai n't ",
        ' Aint ':" Ai n't ",
        ' arent ':" are n't ",
        ' Arent ':" Are n't ",
        ' cant ':" ca n't ",
        ' Cant ':" Ca n't ",
        ' couldve ':" could 've ",
        ' Couldve ':" Could 've ",
        ' couldnt ':" could n't ",
        ' Couldnt ':" Could n't ",
        ' darent ':" dare n't",
        ' Darent ':" Dare n't",
        ' didnt ':" did n't ",
        ' Didnt ':" Did n't ",
        ' doesnt ':" does n't ",
        ' Doesnt ':" Does n't ",
        ' dont ':" do n't ",
        ' Dont ':" Do n't ",
        ' gotta ':' got ta ',
        ' Gotta ':' Got ta ',
        ' hadnt ':" had n't ",
        ' Hadnt ':" Had n't ",
        ' hasnt ':" has n't ",
        ' Hasnt ':" Has n't ",
        ' havent ':" have n't ",
		' hes ':" he 's ",
		' Hes ':" He 's ",
        ' hed ':" he 'd ",
        ' Hed ':" He 'd ",
        ' howd ':" how 'd ",
        ' Howd ':" How 'd ",
        ' howll ':" how 'll ",
        ' Howll ':" How 'll ",
        ' howre ':" how 're ",
        ' Howre ':" How 're ",
        ' id ':" i 'd ",
        ' Id ':" I 'd ",
        ' im ':" i 'm ",
        ' Im ':" I 'm ",
        ' ive ':" i 've ",
        ' Ive ':" I 've ",
        ' isnt ':" is n't ",
        ' Isnt ':" Is n't ",
		' its ':" it 's ",
		' Its ':" It 's ",
        ' itd ':" it 'd ",
        ' Itd ':" It 'd ",
        ' itll ':" it 'll ",
        ' Itll ':" It 'll ",
        ' lets ':" let 's ",
        ' Lets ':" Let 's ",
        ' mayve ':" may 've ",
        ' Mayve ':" May 've ",
        ' mightnt ':" might n't ",
        ' Mightnt ':" Might n't ",
        ' mightve ':" might 've ",
        ' Mightve ':" Might 've ",
        ' mustnt ':" must n't ",
        ' Mustnt ':" Must n't ",
        ' mustve ':" must 've ",
        ' Mustve ':" Must 've ",
        ' neednt ':" need n't ",
        ' Neednt ':" Need n't ",
        ' oughtnt ':" ought n't ",
        ' Oughtnt ':" Ought n't ",
        ' shant ':" sha n't ",
        ' Shant ':" Sha n't ",
		' shes ':" she 's ",
		' Shes ':" She 's ",
        ' shouldve ':" should 've ",
        ' Shouldve ':" Should 've ",
        ' shouldnt ':" should n't ",
        ' Shouldnt ':" Should n't ",
        ' somebodys ':" somebody 's ",
        ' Somebodys ':" Somebody 's ",
        ' someones ':" someone 's ",
        ' Someones ':" Someone 's ",
        ' somethings ': " something 's ",
        ' Somethings ': " Something 's ",
        ' thatll ':" that 'll ",
        ' Thatll ':" That 'll ",
        ' thats ':" that 's ",
        ' Thats ':" That 's ",
        ' thatd ':" that 'd ",
        ' Thatd ':" That 'd ",
        ' thered ':" there 'd ",
        ' Thered ':" There 'd ",
        ' theres ':" there 's ",
        ' Theres ':" There 's ",
        ' theyd ':" they 'd ",
        ' Theyd ':" They 'd ",
        ' theyll ':" they 'll ",
        ' Theyll ':" They 'll ",
        ' theyre ':" they 're ",
        ' Theyre ':" They 're ",
        ' theyve ':" they 've ",
        ' Theyve ':" They 've ",
        ' tis ':" 't is ",
        ' Tis ':" 'T is ",
        ' twas ':" 't was ",
        ' Twas ':" 'T was ",
        ' wasnt ':" was n't ",
        ' Wasnt ':" Was n't ",
        ' wedve ':" we 'd 've ",
        ' Wedve ':" We 'd 've ",
        ' weve ':" we 've ",
        ' Weve ':" We 've ",
        ' werent ':" were n't ",
        ' Werent ':" Were n't ",
        ' whatd ':" what 'd ",
        ' Whatd ':" What 'd ",
        ' whatll ':" what 'll ",
        ' Whatll ':" What 'll ",
        ' whats ':" what 's ",
        ' Whats ':" What 's ",
        ' whatve ':" what 've ",
        ' Whatve ':" What 've ",
        ' whichs ':" which 's ",
        ' Whichs ':" Which 's ",
        ' whod ':" who 'd ",
        ' Whod ':" Who 'd ",
        ' wholl ':" who 'll ",
        ' Wholl ':" Who 'll ",
        ' whos ':" who 's ",
        ' Whos ':" Who 's ",
        ' whove ':" who 've ",
        ' Whove ':" Who 've ",
        ' whyd ':" why 'd ",
        ' Whyd ':" Why 'd ",
        ' whyre ':" why 're ",
        ' Whyre ':" Why 're ",
        ' whys ' :" why 's ",
        ' Whys ' :" Why 's ",
        ' wont ':" wo n't ",
        ' Wont ':" Wo n't ",
        ' wouldve ':" would 've ",
        ' Wouldve ':" Would 've ",
        ' yall ':" y' all ",
        ' Yall ':" Y' all ",
        ' youd ':" you 'd ",
        ' Youd ':" You 'd ",
        ' youll ':" you 'll ",
        ' Youll ':" You 'll ",
        ' youre ':" you 're ",
        ' Youre ':" You 're ",
        ' youve ':" you 've ",       
        ' Youve ':" You 've ",
        ' dunno ':" do n't know ",
        ' Dunno ':" Do n't know ",        
    }
    words = ' '+ ' '.join(words.replace('\n','').split()) + ' '
    for contraction,replacement in punctuation.items():
        words = words.replace(contraction,replacement)
    return words[1:-1].split()

